

default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5

development:
  <<: *default
  database: ping-pong_development


test:
  <<: *default
  database: ping-pong_test



# production:
#   <<: *default
#   database: ping-ping_production
#   username: instagram-clone
#   password: <%= ENV['INSTAGRAM-CLONE_DATABASE_PASSWORD'] %>
